[versions]
# Plugins
agp = "8.9.0"
dokka = "1.9.20"
spotless = "7.0.2"
mavenPublish = "0.31.0"
bcv = "0.17.0"
gver = "0.52.0"

# Kotlin
kotlin = "2.1.10"
kotlinCoroutines = "1.10.1"

# Androidx
androidxCore = "1.15.0"
androidxAnnotation = "1.9.1"
androidxAppcompat = "1.7.0"
androidxDrawerlayout = "1.2.0"
androidxLeanback = "1.0.0"
androidxNavigation = "2.8.7"
androidxRecyclerview = "1.4.0"
androidxSlidingpanelayout = "1.2.0"
androidxSwiperefreshlayout = "1.1.0"
androidxViewpager = "1.1.0"
androidxViewpager2 = "1.1.0"
androidxLifecycle = "2.8.7"
androidxActivity = "1.10.1"
androidxFragment = "1.8.6"
androidxConstraintlayout = "2.2.1"

# Google
material = "1.12.0"

# Lint
ktlint = "1.2.1"


[libraries]
# Kotlin
kotlin-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "kotlinCoroutines" }

# Androidx
androidx-core = { module = "androidx.core:core", version.ref = "androidxCore" }
androidx-annotation = { module = "androidx.annotation:annotation", version.ref = "androidxAnnotation" }
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "androidxAppcompat" }
androidx-drawerlayout = { module = "androidx.drawerlayout:drawerlayout", version.ref = "androidxDrawerlayout" }
androidx-leanback = { module = "androidx.leanback:leanback", version.ref = "androidxLeanback" }
androidx-navigation = { module = "androidx.navigation:navigation-runtime", version.ref = "androidxNavigation" }
androidx-recyclerview = { module = "androidx.recyclerview:recyclerview", version.ref = "androidxRecyclerview" }
androidx-slidingpanelayout = { module = "androidx.slidingpanelayout:slidingpanelayout", version.ref = "androidxSlidingpanelayout" }
androidx-swiperefreshlayout = { module = "androidx.swiperefreshlayout:swiperefreshlayout", version.ref = "androidxSwiperefreshlayout" }
androidx-viewpager = { module = "androidx.viewpager:viewpager", version.ref = "androidxViewpager" }
androidx-viewpager2 = { module = "androidx.viewpager2:viewpager2", version.ref = "androidxViewpager2" }
androidx-lifecycle-runtime = { module = "androidx.lifecycle:lifecycle-runtime", version.ref = "androidxLifecycle" }
androidx-activity = { module = "androidx.activity:activity", version.ref = "androidxActivity" }
androidx-fragment = { module = "androidx.fragment:fragment", version.ref = "androidxFragment" }
androidx-constraintlayout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "androidxConstraintlayout" }

# Google
material = { module = "com.google.android.material:material", version.ref = "material" }


# build-logic
android-gradlePlugin = { module = "com.android.tools.build:gradle", version.ref = "agp" }
kotlin-gradlePlugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
dokka-gradlePlugin = { module = "org.jetbrains.dokka:dokka-gradle-plugin", version.ref = "dokka" }
spotless-gradlePlugin = { module = "com.diffplug.spotless:spotless-plugin-gradle", version.ref = "spotless" }


[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
spotless = { id = "com.diffplug.spotless", version.ref = "spotless" }
maven-publish = { id = "com.vanniktech.maven.publish", version.ref = "mavenPublish" }
binary-compatibility-validator = { id = "org.jetbrains.kotlinx.binary-compatibility-validator", version.ref = "bcv" }
gver = { id = "com.github.ben-manes.versions", version.ref = "gver" }
