[versions]
spotless = "6.8.0"
gver = "0.44.0"
detekt = "1.22.0"
dokka = "1.7.20"
maven-publish = "0.22.0"

plugin-android = "7.3.1"

kotlin = "1.7.21"
kotlin-coroutines = "1.6.4"

androidx-core = "1.9.0"
androidx-annotation = "1.5.0"
androidx-appcompat = "1.5.1"
androidx-drawerlayout = "1.1.1"
androidx-leanback = "1.0.0"
androidx-navigation = "2.5.3"
androidx-recyclerview = "1.2.1"
androidx-slidingpanelayout = "1.2.0"
androidx-swiperefreshlayout = "1.1.0"
androidx-viewpager = "1.0.0"
androidx-viewpager2 = "1.0.0"
androidx-lifecycle = "2.5.1"
androidx-activity = "1.6.1"
androidx-fragment = "1.5.5"
androidx-constraintlayout = "2.1.4"

material = "1.8.0-beta01"

ktlint = "0.46.1"


[plugins]
spotless = { id = "com.diffplug.spotless", version.ref = "spotless" }
gver = { id = "com.github.ben-manes.versions", version.ref = "gver" }
detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detekt" }
dokka = { id = "org.jetbrains.dokka", version.ref = "dokka" }


[libraries]
android-gradlePlugin = { module = "com.android.tools.build:gradle", version.ref = "plugin-android" }
kotlin-gradlePlugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
dokka-gradlePlugin = { module = "org.jetbrains.dokka:dokka-gradle-plugin", version.ref = "dokka" }
publish-gradlePlugin = { module = "com.vanniktech:gradle-maven-publish-plugin", version.ref = "maven-publish" }
spotless-gradlePlugin = { module = "com.diffplug.spotless:spotless-plugin-gradle", version.ref = "spotless" }

kotlin-stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib-jdk8", version.ref = "kotlin" }
kotlin-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "kotlin-coroutines" }

androidx-core = { module = "androidx.core:core", version.ref = "androidx-core" }
androidx-annotation = { module = "androidx.annotation:annotation", version.ref = "androidx-annotation" }
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "androidx-appcompat" }
androidx-drawerlayout = { module = "androidx.drawerlayout:drawerlayout", version.ref = "androidx-drawerlayout" }
androidx-leanback = { module = "androidx.leanback:leanback", version.ref = "androidx-leanback" }
androidx-navigation = { module = "androidx.navigation:navigation-runtime", version.ref = "androidx-navigation" }
androidx-recyclerview = { module = "androidx.recyclerview:recyclerview", version.ref = "androidx-recyclerview" }
androidx-slidingpanelayout = { module = "androidx.slidingpanelayout:slidingpanelayout", version.ref = "androidx-slidingpanelayout" }
androidx-swiperefreshlayout = { module = "androidx.swiperefreshlayout:swiperefreshlayout", version.ref = "androidx-swiperefreshlayout" }
androidx-viewpager = { module = "androidx.viewpager:viewpager", version.ref = "androidx-viewpager" }
androidx-viewpager2 = { module = "androidx.viewpager2:viewpager2", version.ref = "androidx-viewpager2" }
androidx-lifecycle-runtime-ktx = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "androidx-lifecycle" }
androidx-activity = { module = "androidx.activity:activity", version.ref = "androidx-activity" }
androidx-fragment = { module = "androidx.fragment:fragment", version.ref = "androidx-fragment" }
androidx-constraintlayout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "androidx-constraintlayout" }

material = { module = "com.google.android.material:material", version.ref = "material" }


[bundles]
plugins = [
    "android-gradlePlugin",
    "kotlin-gradlePlugin",
    "dokka-gradlePlugin",
    "publish-gradlePlugin"
]
